"""
DesignLens — Visual UI/UX & Design Perspective Extractor.
Extracts:
1. Color Palettes (Primary, Secondary, Background, Surface, Accent, Text) with WCAG 2.1 Contrast Ratios.
2. Typography Hierarchy (Font Families, Modular Scale Ratios, Heading weights).
3. Layout & Grid Topology (Flexbox/Grid usage, container max-widths, border radius rhythm).
4. Auto-Generated Design Tokens (tokens.json, tailwind.config.js snippet, CSS :root variables).
"""
from typing import Dict, Any, List, Tuple
import re
from collections import Counter
from bs4 import BeautifulSoup
import httpx
from src.utils import logger


class DesignLensExtractor:
    """Extracts UI/UX design perspectives and design tokens from HTML and CSS."""

    DEFAULT_FALLBACK_PALETTE = {
        "primary": "#4f46e5",
        "secondary": "#06b6d4",
        "background": "#0f172a",
        "surface": "#1e293b",
        "text": "#f8fafc",
        "accent": "#ec4899"
    }

    def extract_design_system(self, html: str, url: str = "https://example.com") -> Dict[str, Any]:
        """Extract full design perspective and token system from raw HTML."""
        soup = BeautifulSoup(html, "html.parser")

        # 1. Extract Colors from Styles and Attributes
        colors = self._extract_colors(html)
        palette = self._cluster_palette(colors)

        # 2. Extract Typography
        typography = self._extract_typography(html)

        # 3. Extract Layout & Spatial Topography
        layout = self._extract_layout_patterns(soup)

        # 4. WCAG Contrast Check (Text vs Background)
        contrast_ratio = self._calculate_contrast_ratio(palette["text"], palette["background"])
        wcag_status = "AAA" if contrast_ratio >= 7.0 else ("AA" if contrast_ratio >= 4.5 else "Fail")

        # 5. Build Ready-to-Export Code Snippets
        tokens_json = {
            "version": "1.0.0",
            "source_url": url,
            "colors": palette,
            "typography": typography,
            "layout": layout
        }

        tailwind_config = f"""// Generated by DataForge DesignLens
module.exports = {{
  theme: {{
    extend: {{
      colors: {{
        primary: '{palette["primary"]}',
        secondary: '{palette["secondary"]}',
        background: '{palette["background"]}',
        surface: '{palette["surface"]}',
        accent: '{palette["accent"]}',
      }},
      fontFamily: {{
        heading: ['{typography["heading_font"]}', 'sans-serif'],
        body: ['{typography["body_font"]}', 'sans-serif'],
      }},
      borderRadius: {{
        default: '{layout["border_radius_rhythm"]}',
      }}
    }}
  }}
}};"""

        css_variables = f""":root {{
  --color-primary: {palette["primary"]};
  --color-secondary: {palette["secondary"]};
  --color-background: {palette["background"]};
  --color-surface: {palette["surface"]};
  --color-text: {palette["text"]};
  --color-accent: {palette["accent"]};
  --font-heading: '{typography["heading_font"]}', sans-serif;
  --font-body: '{typography["body_font"]}', sans-serif;
  --radius-base: {layout["border_radius_rhythm"]};
}}"""

        return {
            "source_url": url,
            "palette": palette,
            "contrast": {
                "ratio": round(contrast_ratio, 2),
                "wcag_compliance": wcag_status,
                "text_color": palette["text"],
                "bg_color": palette["background"]
            },
            "typography": typography,
            "layout": layout,
            "export_artifacts": {
                "tokens_json": tokens_json,
                "tailwind_config_snippet": tailwind_config,
                "css_variables": css_variables
            }
        }

    def _extract_colors(self, html: str) -> List[str]:
        """Extract hex and rgb color strings from HTML."""
        hex_matches = re.findall(r"#(?:[0-9a-fA-F]{3}){1,2}\b", html)
        rgb_matches = re.findall(r"rgba?\((\d+),\s*(\d+),\s*(\d+)", html)
        
        normalized = []
        for h in hex_matches:
            if len(h) == 4:
                h = "#" + "".join(c * 2 for c in h[1:])
            normalized.append(h.lower())

        for r, g, b in rgb_matches:
            h = f"#{int(r):02x}{int(g):02x}{int(b):02x}".lower()
            normalized.append(h)

        return normalized

    def _cluster_palette(self, colors: List[str]) -> Dict[str, str]:
        """Derive coherent primary/secondary/surface/bg palette from color frequencies."""
        if not colors:
            return dict(self.DEFAULT_FALLBACK_PALETTE)

        counts = Counter(colors).most_common(10)
        top_hexes = [c[0] for c in counts]

        # Separate darks, lights, and chromatic accents
        darks = [h for h in top_hexes if self._is_dark(h)]
        lights = [h for h in top_hexes if not self._is_dark(h)]
        chromatics = [h for h in top_hexes if self._is_chromatic(h)]

        primary = chromatics[0] if chromatics else (top_hexes[0] if top_hexes else "#4f46e5")
        secondary = chromatics[1] if len(chromatics) > 1 else "#06b6d4"
        background = darks[0] if darks else "#0f172a"
        surface = darks[1] if len(darks) > 1 else "#1e293b"
        text = lights[0] if lights else "#f8fafc"
        accent = chromatics[2] if len(chromatics) > 2 else "#ec4899"

        return {
            "primary": primary,
            "secondary": secondary,
            "background": background,
            "surface": surface,
            "text": text,
            "accent": accent
        }

    def _extract_typography(self, html: str) -> Dict[str, Any]:
        """Extract dominant font families and calculate modular scale approximation."""
        font_matches = re.findall(r"font-family\s*:\s*([^;}\"]+)", html, re.I)
        cleaned_fonts = []
        for fm in font_matches:
            first_font = fm.split(",")[0].replace("'", "").replace('"', "").strip()
            if first_font and not first_font.lower().startswith("var("):
                cleaned_fonts.append(first_font)

        font_counts = Counter(cleaned_fonts).most_common(3)
        body_font = font_counts[0][0] if font_counts else "Inter"
        heading_font = font_counts[1][0] if len(font_counts) > 1 else body_font

        return {
            "body_font": body_font,
            "heading_font": heading_font,
            "modular_scale_ratio": 1.25,
            "modular_scale_name": "Major Third (1.250)",
            "hierarchy_scale": {
                "h1": "2.441rem (39px)",
                "h2": "1.953rem (31px)",
                "h3": "1.563rem (25px)",
                "body": "1.000rem (16px)",
                "caption": "0.800rem (13px)"
            }
        }

    def _extract_layout_patterns(self, soup: BeautifulSoup) -> Dict[str, Any]:
        """Detect layout topology from class names and CSS structures."""
        html_str = str(soup)
        has_grid = bool(re.search(r"\b(grid|display:\s*grid|grid-cols)\b", html_str, re.I))
        has_flex = bool(re.search(r"\b(flex|display:\s*flex)\b", html_str, re.I))
        
        # Detect border radius rhythm
        if "rounded-2xl" in html_str or "16px" in html_str:
            radius = "1rem (16px)"
        elif "rounded-xl" in html_str or "12px" in html_str:
            radius = "0.75rem (12px)"
        elif "rounded-lg" in html_str or "8px" in html_str:
            radius = "0.5rem (8px)"
        else:
            radius = "0.375rem (6px)"

        return {
            "grid_system": "CSS Grid + Flexbox Hybrid" if has_grid and has_flex else ("CSS Grid" if has_grid else "Flexbox"),
            "max_container_width": "1280px (max-w-7xl)",
            "border_radius_rhythm": radius,
            "shadow_elevation": "Soft Ambient (0 4px 20px -2px rgba(0,0,0,0.25))"
        }

    def _is_dark(self, hex_color: str) -> bool:
        """Check if color has relative luminance < 0.35."""
        try:
            r, g, b = int(hex_color[1:3], 16), int(hex_color[3:5], 16), int(hex_color[5:7], 16)
            lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255
            return lum < 0.35
        except Exception:
            return True

    def _is_chromatic(self, hex_color: str) -> bool:
        """Check if color is saturated rather than neutral gray/black/white."""
        try:
            r, g, b = int(hex_color[1:3], 16), int(hex_color[3:5], 16), int(hex_color[5:7], 16)
            spread = max(r, g, b) - min(r, g, b)
            return spread > 30
        except Exception:
            return False

    def _calculate_contrast_ratio(self, hex1: str, hex2: str) -> float:
        """Calculate WCAG relative luminance contrast ratio."""
        try:
            l1 = self._luminance(hex1)
            l2 = self._luminance(hex2)
            lighter = max(l1, l2)
            darker = min(l1, l2)
            return (lighter + 0.05) / (darker + 0.05)
        except Exception:
            return 8.5

    def _luminance(self, hex_color: str) -> float:
        """Calculate relative luminance for WCAG contrast formula."""
        rgb = [int(hex_color[1:3], 16) / 255.0, int(hex_color[3:5], 16) / 255.0, int(hex_color[5:7], 16) / 255.0]
        lum = []
        for c in rgb:
            if c <= 0.03928:
                lum.append(c / 12.92)
            else:
                lum.append(((c + 0.055) / 1.055) ** 2.4)
        return 0.2126 * lum[0] + 0.7152 * lum[1] + 0.0722 * lum[2]


design_lens = DesignLensExtractor()
