"""Generates reproducible, defensible Jupyter Notebooks with Sandbox Assertions."""
import json
import os
import nbformat
from datetime import datetime
from src.storage import ensure_local
from src.utils import logger


def generate_notebook(dataset_id):
    prof_path = ensure_local(f"reports/profile_{dataset_id}.json")
    exec_path = ensure_local(f"reports/execution_{dataset_id}.json")

    if not prof_path or not exec_path or not os.path.exists(prof_path) or not os.path.exists(exec_path):
        raise ValueError("Dataset must be profiled and cleaned before exporting notebook.")

    profile = json.load(open(prof_path, encoding="utf-8"))
    execution = json.load(open(exec_path, encoding="utf-8"))

    nb = nbformat.v4.new_notebook()
    nb.metadata.kernelspec = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3"
    }

    cells = []

    # 1. Title & Metadata
    cells.append(nbformat.v4.new_markdown_cell(
        f"# DataForge AI Pipeline Export\n\n"
        f"**Dataset ID:** `{dataset_id}`\n\n"
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        f"**Original Rows:** {profile.get('total_rows', 0):,} | **Original Columns:** {profile.get('total_columns', 0)}"
    ))

    # 2. Imports
    cells.append(nbformat.v4.new_code_cell(
        "import pandas as pd\n"
        "import numpy as np\n\n"
        "# DataForge AI: Reproducible Pipeline with Anti-Hallucination Assertions"
    ))

    # 3. Load Raw Data
    raw_csv = profile.get("snapshot", {}).get("csv", f"data/canonical/{dataset_id}.csv")
    cells.append(nbformat.v4.new_markdown_cell("## 1. Ingest Raw Data"))
    cells.append(nbformat.v4.new_code_cell(
        f"# Load the original raw dataset\n"
        f"raw_df = pd.read_csv('{raw_csv}')\n"
        f"df = raw_df.copy()\n\n"
        f"print(f'Loaded {{len(df):,}} rows and {{len(df.columns)}} columns.')"
    ))

    # 4. Pipeline Steps
    cells.append(nbformat.v4.new_markdown_cell(
        "## 2. Cleaning Pipeline & Verification Assertions\n\n"
        "Each step below includes deterministic `assert` statements generated by the "
        "DataForge Anti-Hallucination Sandbox. If these assertions fail on future runs, "
        "the underlying data distribution has drifted."
    ))

    current_rows = profile.get("total_rows", len(profile.get("columns", [])))

    steps = execution.get("steps") or execution.get("report") or []
    for step in steps:
        action = step.get("action", "")
        col = step.get("column") or "N/A"
        desc = step.get("description") or step.get("reason") or action
        impact = step.get("impact", {})
        verification = step.get("verification", {})

        cells.append(nbformat.v4.new_markdown_cell(
            f"### Step: {action.replace('_', ' ').title()}\n\n"
            f"**Target Column:** `{col}`\n\n"
            f"**Description:** {desc}\n\n"
            f"**Expected Impact:** {impact}"
        ))

        code = _generate_step_code(action, col, step)
        cells.append(nbformat.v4.new_code_cell(code))

        asserts = _generate_assertions(action, col, step, current_rows, verification)
        if asserts:
            cells.append(nbformat.v4.new_code_cell(
                "# 🛡️ DataForge Sandbox Verification Assertions\n" + asserts
            ))

        if "rows_after" in step:
            current_rows = step["rows_after"]
        elif action in ["remove_duplicates", "remove_outliers", "remove_orphans", "drop_null_rows"]:
            current_rows -= impact.get("rows_removed", impact.get("rows_affected", 0))

    # 5. Final Export
    cells.append(nbformat.v4.new_markdown_cell("## 3. Export Cleaned Data"))
    cells.append(nbformat.v4.new_code_cell(
        f"# Save the mathematically verified cleaned dataset\n"
        f"df.to_csv('data/canonical/{dataset_id}_cleaned_reproducible.csv', index=False)\n"
        f"print(f'Exported {{len(df):,}} verified rows.')"
    ))

    nb.cells = cells
    logger.info(f"[notebook] Generated reproducible notebook for {dataset_id}")
    return nb


def _generate_step_code(action, col, step):
    if action == "remove_duplicates":
        subset = step.get("subset")
        return f"df = df.drop_duplicates(subset={subset})" if subset else "df = df.drop_duplicates()"
    if action == "fill_nulls":
        return (f"# Fill nulls in '{col}'\n"
                f"if pd.api.types.is_numeric_dtype(df['{col}']):\n"
                f"    df['{col}'] = df['{col}'].fillna(df['{col}'].median())\n"
                f"else:\n"
                f"    mode_val = df['{col}'].mode()\n"
                f"    df['{col}'] = df['{col}'].fillna(mode_val[0] if not mode_val.empty else 'Unknown')")
    if action == "remove_outliers":
        return (f"q1, q3 = df['{col}'].quantile([0.25, 0.75])\n"
                f"iqr = q3 - q1\n"
                f"df = df[(df['{col}'] >= q1 - 1.5*iqr) & (df['{col}'] <= q3 + 1.5*iqr)]")
    if action == "standardize_text":
        return (f"df['{col}'] = df['{col}'].astype(str).str.strip().str.title()\n"
                f"df.loc[df['{col}'].str.lower() == 'nan', '{col}'] = np.nan # Preserve NaNs")
    if action == "cast_dtype":
        target = step.get("target_dtype", "float64")
        if "float" in target or "int" in target:
            return f"df['{col}'] = pd.to_numeric(df['{col}'], errors='coerce')"
        return f"df['{col}'] = df['{col}'].astype('{target}')"
    if action == "clip_values":
        return f"df['{col}'] = df['{col}'].clip(lower={step.get('lo')}, upper={step.get('hi')})"
    if action == "derive_metric":
        expr = step.get("pandas_expr") or step.get("expr", "")
        new_col = step.get("new_column", "derived_metric")
        return f"df['{new_col}'] = df.eval('{expr}')"

    return f"# Complex/Custom step: {action}\n# Review DataForge execution report for exact logic."


def _generate_assertions(action, col, step, current_rows, verification):
    asserts = []
    rows_after = step.get("rows_after", current_rows)

    if action in ["standardize_text", "cast_dtype", "clip_values", "derive_metric", "fill_nulls"]:
        asserts.append(f"assert len(df) == {current_rows}, f'Row budget invariant failed: expected {current_rows}, got {{len(df)}}'")
    else:
        asserts.append(f"assert len(df) == {rows_after}, f'Row count mismatch: expected {rows_after}, got {{len(df)}}'")

    if action == "fill_nulls":
        asserts.append(f"assert df['{col}'].isna().sum() == 0, f'Null reduction failed: {{df[\"{col}\"].isna().sum()}} nulls remaining'")

    if action == "cast_dtype":
        target = step.get("target_dtype", "float64")
        asserts.append(f"assert str(df['{col}'].dtype).startswith('{target[:4]}'), f'Type safety failed: expected {target}, got {{df[\"{col}\"].dtype}}'")

    if action == "clip_values":
        lo, hi = step.get("lo"), step.get("hi")
        if lo is not None:
            asserts.append(f"assert df['{col}'].min() >= {lo}, 'Lower bound violated'")
        if hi is not None:
            asserts.append(f"assert df['{col}'].max() <= {hi}, 'Upper bound violated'")

    if action == "remove_outliers":
        asserts.append(
            f"q1, q3 = df['{col}'].quantile([0.25, 0.75])\n"
            f"iqr = q3 - q1\n"
            f"assert df['{col}'].min() >= (q1 - 1.5*iqr) - 1e-9, 'Outlier lower bound violated'\n"
            f"assert df['{col}'].max() <= (q3 + 1.5*iqr) + 1e-9, 'Outlier upper bound violated'"
        )

    return "\n".join(asserts) if asserts else ""
